#!/bin/csh -f

if ($?VERDI_HOME) then
  if (-e $VERDI_HOME/bin/verdi) then
    echo "***Info: Invoking verdi from $VERDI_HOME/bin/verdi"
    $VERDI_HOME/bin/verdi -nologo -rcFile hc.rc -ssr _hardcopy.snapshot
  else
    echo "***Warning: $VERDI_HOME/bin/verdi doesn't exist."
  endif
else
  echo "***Info: Invoking verdi from the default path `which verdi`"
  verdi -nologo -rcFile hc.rc -ssr _hardcopy.snapshot
endif
